name: Generate project pages

on:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run generator (Node)
        run: node scripts/generate-project-pages.js

      - name: Commit generated pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add projects || true
          git commit -m "chore: generate project pages" || echo "No changes to commit"
          git push
